import { test } from './fixtures/extension';
import { openPages } from './fixtures/observe';
import { observeAndSanitize } from './fixtures/sanitize';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Page } from '@playwright/test';

/**
 * Stage 2 Part I measurements: how long the privacy pipeline takes, and how big the payload it
 * produces is in each capture mode. Measurement only — latency budgets are enforced in Stage 8
 * (docs/STAGES.md).
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(__dirname, '..', '..', 'eval', 'reports');
const RUNS = 10;

function percentile(values: number[], p: number): number {
  const sorted = [...values].sort((a, b) => a - b);
  const index = Math.min(sorted.length - 1, Math.max(0, Math.ceil((p / 100) * sorted.length) - 1));
  return sorted[index]!;
}

function stat(values: number[]): { median: number; p95: number } {
  return { median: Number(percentile(values, 50).toFixed(1)), p95: Number(percentile(values, 95).toFixed(1)) };
}

async function setMode(panelPage: Page, mode: string): Promise<void> {
  // Not `.locator('select').first()`: TaskPanel (Stage 3B) now renders its own `<select>`s
  // (task-data category, task mode) ahead of this one in the DOM, so position is no longer
  // unique. "Mode" (this measurement UI's own select) and TaskPanel's "Task mode" both contain
  // "mode", so this needs an exact match.
  await panelPage.getByLabel('Mode', { exact: true }).selectOption(mode);
}

test('privacy pipeline timings and payload sizes', async ({ context, sidepanelUrl }) => {
  test.setTimeout(600_000);

  const lines: string[] = [
    '# Stage 2.5 — privacy pipeline timings and payload sizes',
    '',
    `Generated by \`extension/e2e/privacy-timings.spec.ts\` on ${new Date().toISOString().slice(0, 10)}.`,
    `${RUNS} observations per page at the top viewport, balanced mode: first NEW_SCREEN then repeated captures. DOM detection/redaction still run on SAME_SCREEN; the router omits the outbound image. Measurement only — Stage 8 sets the budgets.`,
    '',
    '## Pipeline stages (ms)',
    '',
    '| Page | Stage | Median | p95 |',
    '| --- | --- | ---: | ---: |',
  ];

  for (const pageName of ['kyc.html', 'pii-zoo.html']) {
    const { targetPage, panelPage } = await openPages(context, sidepanelUrl, `/${pageName}`);
    const detect: number[] = [];
    const policy: number[] = [];
    const redactMs: number[] = [];
    const sealMs: number[] = [];
    const schema: number[] = [];
    const ruleScan: number[] = [];
    const leak: number[] = [];
    const coverage: number[] = [];
    const masks: number[] = [];

    for (let i = 0; i < RUNS; i++) {
      const { preview } = await observeAndSanitize(panelPage, targetPage);
      detect.push(preview.timings.detectMs);
      policy.push(preview.timings.policyMs);
      redactMs.push(preview.timings.redactMs);
      sealMs.push(preview.timings.sealMs);
      schema.push(preview.sealTimings.schemaMs);
      ruleScan.push(preview.sealTimings.ruleScanMs);
      leak.push(preview.sealTimings.leakCheckMs);
      coverage.push(preview.sealTimings.coverageMs);
      masks.push(preview.sealTimings.maskIntegrityMs);
    }

    for (const [label, values] of [
      ['detect', detect],
      ['policy', policy],
      ['redact', redactMs],
      ['seal (total)', sealMs],
      ['seal — schema', schema],
      ['seal — rule scan', ruleScan],
      ['seal — leak check', leak],
      ['seal — coverage', coverage],
      ['seal — mask integrity', masks],
    ] as const) {
      const { median, p95 } = stat([...values]);
      lines.push(`| ${pageName} | ${label} | ${median} | ${p95} |`);
    }

    await targetPage.close();
    await panelPage.close();
  }

  lines.push('');
  lines.push('## Payload size by capture mode (pii-zoo.html)');
  lines.push('');
  lines.push('Fresh page/session per mode (NEW_SCREEN). PNG image size below is the serialized data-URL contribution, including base64; the remainder includes JSON structure.');
  lines.push('');
  lines.push('| Mode | Sealed bytes | Image data-URL bytes | Other bytes |');
  lines.push('| --- | ---: | ---: | ---: |');

  {
    for (const mode of ['fast', 'balanced', 'accurate']) {
      const { targetPage, panelPage } = await openPages(context, sidepanelUrl, '/pii-zoo.html');
      await setMode(panelPage, mode);
      const { preview } = await observeAndSanitize(panelPage, targetPage);
      const imageBytes = (JSON.parse(preview.draftJson) as { image?: string }).image?.length ?? 0;
      lines.push(`| ${mode} | ${preview.size} | ${imageBytes} | ${preview.size - imageBytes} |`);
      await targetPage.close();
      await panelPage.close();
    }

    // Replay/screenshot recording is off. Stage 4 will provide explicit local Eval
    // capture with expiry; no raw screenshot artifacts are persisted by this benchmark.

  }

  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(path.join(OUT_DIR, 'stage2-timings.md'), lines.join('\n'), 'utf8');
  console.log(lines.join('\n'));
});
