/**
 * The PII category and policy action enums (Stage 2 Part B/C). Mirrors docs/policy.yaml exactly —
 * `privacy/policyData.ts` (generated by `pnpm gen:policy`) is checked against this file and the
 * YAML by `privacy/__tests__/policyData.test.ts`.
 */

export type Category =
  // never_automated
  | 'OTP'
  | 'CVV'
  | 'UPI_PIN'
  | 'SECRET'
  // credential
  | 'PASSWORD'
  // high
  | 'AADHAAR'
  | 'PAN'
  | 'CARD_NUMBER'
  | 'BANK_ACCOUNT'
  | 'UPI_ID'
  // medium
  | 'NAME'
  | 'PHONE'
  | 'EMAIL'
  | 'ADDRESS'
  | 'DOB'
  | 'HEALTH'
  | 'VEHICLE_REG'
  | 'FINANCIAL_VALUE'
  | 'PRIVATE_GENERIC'
  // biometric
  | 'FACE'
  | 'PHOTO'
  // documents
  | 'ID_DOCUMENT'
  | 'CARD_IMAGE'
  | 'SIGNATURE'
  | 'QR'
  | 'UNSCANNED_MEDIA'
  // quasi
  | 'CITY'
  | 'PIN_CODE'
  | 'EMPLOYER'
  | 'DATE'
  | 'ORDER_ID'
  | 'IFSC';

export const ALL_CATEGORIES: Category[] = [
  'OTP',
  'CVV',
  'UPI_PIN',
  'SECRET',
  'PASSWORD',
  'AADHAAR',
  'PAN',
  'CARD_NUMBER',
  'BANK_ACCOUNT',
  'UPI_ID',
  'NAME',
  'PHONE',
  'EMAIL',
  'ADDRESS',
  'DOB',
  'HEALTH',
  'VEHICLE_REG',
  'FINANCIAL_VALUE',
  'PRIVATE_GENERIC',
  'FACE',
  'PHOTO',
  'ID_DOCUMENT',
  'CARD_IMAGE',
  'SIGNATURE',
  'QR',
  'UNSCANNED_MEDIA',
  'CITY',
  'PIN_CODE',
  'EMPLOYER',
  'DATE',
  'ORDER_ID',
  'IFSC',
];

export type PolicyClass = 'never_automated' | 'credential' | 'high' | 'medium' | 'biometric' | 'documents' | 'quasi' | 'non_pii';

export type Action =
  | 'ALLOW'
  | 'TOKEN'
  | 'TOKEN_WITH_APPROVAL'
  | 'FILL'
  | 'FILL_REGION'
  | 'BLUR'
  | 'USER_ENTERS'
  | 'USER_PROVIDED_ORIGIN_BOUND';
